name: CI-CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build and push Docker images
        uses: docker/build-push-action@v2.6.1
        with:
          context: ./src
          file: ./src/Dockerfile
          push: true
          tags: |
            imgabreuw/rotten-potatoes:latest
            imgabreuw/rotten-potatoes:${{ github.run_number }}
